[tool.poetry]
name = "erroranalysis"
version = "0.1.0"
description = ""
authors = ["AnneliesVlaar <66774020+AnneliesVlaar@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
table = "erroranalysis.data_analysis:table"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"